name: machine spawn

on: [push, pull_request]

jobs:
  wait:
    runs-on: [self-hosted]
    name: testing
    steps:
    - uses: actions/checkout@v1
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with:
        time: '30s'
    - name: Building image
      run: |
          sleep 5m
          echo "testing complete"
