name: Docker Release

on:
  release:
    types: [created]

jobs:
  release:
    name: Docker publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Building image
      run: |
          echo "testing complete"
