name: Github Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: making release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          cat .version | xargs -I% curl -H "Authorization: token $GITHUB_TOKEN" --data '{"tag_name": "test-'%'","target_commitish": "master","name": "test-'%'","draft": false,"prerelease": false}' https://api.github.com/repos/nudjur/deepql/releases
